# Delivery Headless service, needed for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: delivery-service-headless
spec:
  clusterIP: None
  selector:
    component: delivery
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
# Delivery Deployment
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: delivery
spec:
  serviceName: delivery-service-headless
  replicas: 1
  selector:
    matchLabels:
      component: delivery
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
  template:
    metadata:
      labels:
        component: delivery
    spec:
      volumes:
        # Uncomment if using the Git SSH server instead of the Git HTTPS server in Authoring
        # - name: ssh-keys
        #   secret:
        #     secretName: ssh-keys
        - name: deployer-config
          configMap:
            name: deployer-config
        - name: temp
          emptyDir: {}
        - name: logs
          emptyDir: {}
      containers:
        # Elasticsearch container
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:6.8.6
          readinessProbe:
            httpGet:
              path: /_cat/nodes?h=uptime
              port: 9200
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /_cat/nodes?h=uptime
              port: 9200
            initialDelaySeconds: 60
            periodSeconds: 10
          ports:
            - containerPort: 9200
          volumeMounts:
            - name: data
              subPath: indexes-es
              mountPath: /usr/share/elasticsearch/data
            - name: logs
              subPath: elasticsearch
              mountPath: /usr/share/elasticsearch/logs
          env:
            - name: discovery.type
              value: single-node
            - name: bootstrap.memory_lock
              value: "true"
            - name: ES_JAVA_OPTS
              value: "-server -Xss1024K -Xmx2G -Dlog4j2.formatMsgNoLookups=true"
        # Tomcat container
        - name: tomcat
          image: craftercms/delivery_tomcat:3.1.21
          readinessProbe:
            httpGet:
              path: /api/1/monitoring/status.json?token=defaultManagementToken
              port: 8080
            initialDelaySeconds: 60
            failureThreshold: 55
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/1/monitoring/status.json?token=defaultManagementToken
              port: 8080
            initialDelaySeconds: 600
            failureThreshold: 5
            timeoutSeconds: 60
            periodSeconds: 60
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: data
              mountPath: /opt/crafter/data
            - name: temp
              mountPath: /opt/crafter/temp
            - name: logs
              mountPath: /opt/crafter/logs
          env:
            - name: CATALINA_OPTS
              value: "-server -Xss1024K -Xms1G -Xmx3G -Dlog4j2.formatMsgNoLookups=true"
        # Deployer container
        - name: deployer
          image: craftercms/deployer:3.1.21
          readinessProbe:
            httpGet:
              path: /api/1/monitoring/status?token=defaultManagementToken
              port: 9191
            initialDelaySeconds: 30
            failureThreshold: 16
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/1/monitoring/status?token=defaultManagementToken
              port: 9191
            initialDelaySeconds: 180
            failureThreshold: 10
            timeoutSeconds: 60
            periodSeconds: 60  
          ports:
            - containerPort: 9191
          volumeMounts:
            # Uncomment if using the Git SSH server instead of the Git HTTPS server in Authoring
            # - name: ssh-keys
            #   mountPath: /opt/crafter/.ssh
            #   readOnly: true
            - name: deployer-config
              subPath: .gitconfig
              mountPath: /home/crafter/.gitconfig
              readOnly: true
            - name: data
              mountPath: /opt/crafter/data
            - name: temp
              mountPath: /opt/crafter/temp
            - name: logs
              mountPath: /opt/crafter/logs
          env:
            - name: DEPLOYER_JAVA_OPTS
              value: "-server -Xss1024K -Xmx2G -Dlog4j2.formatMsgNoLookups=true"