apiVersion: v1
kind: Service
metadata:
  name: delivery-service-headless
spec:
  clusterIP: None
  selector:
    component: delivery
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
# Delivery Deployment
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: delivery
spec:
  serviceName: delivery-service-headless
  replicas: 2
  selector:
    matchLabels:
      component: delivery
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
  template:
    metadata:
      labels:
        component: delivery
    spec:
      volumes:
        - name: ssh-keys
          secret:
            secretName: delivery-ssh-keys
        - name: temp
          emptyDir: {}
        - name: logs
          emptyDir: {}
      containers:
        # Elasticsearch container
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
          readinessProbe:
            httpGet:
              path: /_cat/nodes?h=uptime
              port: 9200
            initialDelaySeconds: 15
            periodSeconds: 10
          ports:
            - containerPort: 9200
          volumeMounts:
            - name: data
              subPath: indexes-es
              mountPath: /usr/share/elasticsearch/data
            - name: logs
              subPath: elasticsearch
              mountPath: /usr/share/elasticsearch/logs
          env:
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: "-server -Xss1024K -XX:MaxRAMPercentage=80.0"
          resources:
            requests:
              cpu: 500m
              memory: 2.5Gi
            limits:
              cpu: 1
              memory: 2.5Gi
        # Tomcat container
        - name: tomcat
          image: craftercms/delivery_tomcat:4.0.1
          startupProbe:
            httpGet:
              path: /api/1/monitoring/status.json?token=defaultManagementToken
              port: 8080
            failureThreshold: 30
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /api/1/monitoring/status.json?token=defaultManagementToken
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/1/monitoring/status.json?token=defaultManagementToken
              port: 8080
            failureThreshold: 10
            timeoutSeconds: 60
            periodSeconds: 60
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: ssh-keys
              mountPath: /opt/crafter/.ssh
              readOnly: true
            - name: data
              mountPath: /opt/crafter/data
            - name: temp
              mountPath: /opt/crafter/temp
            - name: logs
              mountPath: /opt/crafter/logs
          env:
            - name: CATALINA_OPTS
              value: "-server -Xss1024K -XX:MaxRAMPercentage=80.0"
          resources:
            requests:
              cpu: 1
              memory: 4Gi
            limits:
              cpu: 2
              memory: 4Gi
        # Deployer container
        - name: deployer
          image: craftercms/deployer:4.0.1
          startupProbe:
            httpGet:
              path: /api/1/monitoring/status?token=defaultManagementToken
              port: 9191
            failureThreshold: 60
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /api/1/monitoring/status?token=defaultManagementToken
              port: 9191
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/1/monitoring/status?token=defaultManagementToken
              port: 9191
            failureThreshold: 10
            timeoutSeconds: 60
            periodSeconds: 60
          ports:
            - containerPort: 9191
          volumeMounts:
            - name: ssh-keys
              mountPath: /opt/crafter/.ssh
              readOnly: true
            - name: data
              mountPath: /opt/crafter/data
            - name: temp
              mountPath: /opt/crafter/temp
            - name: logs
              mountPath: /opt/crafter/logs
          env:
            - name: DEPLOYER_JAVA_OPTS
              value: "-server -Xss1024K -XX:MaxRAMPercentage=80.0"
          resources:
            requests:
              cpu: 500m
              memory: 2.5Gi
            limits:
              cpu: 1
              memory: 2.5Gi