apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: craftercms
resources:
  - namespace.yaml
  - hazelcast-rbac.yaml
  - authoring-deployment.yaml
configMapGenerator:
  - name: studio-config
    files:
      - resources/config/studio/studio-config-override.yaml
      - resources/config/studio/hazelcast-config.yaml
secretGenerator:
  - name: crafter-license
    files:
      - resources/secrets/crafter.lic
  - name: git-https-server-cert-files
    files:
      # Please remember to generate missing files
      - resources/secrets/git-https-server/server.crt
      - resources/secrets/git-https-server/server.key
  - name: git-https-server-credentials
    literals:
      # NEVER USE THESE IN PROD! These are only provided for demo/testing. Generate the secrets manually with kubectl 
      # or use something like https://external-secrets.io/v0.6.0-rc1/
      - username=crafter
      - password=crafter
