hazelcast:
  network:
    join:
      multicast:
        enabled: false
      kubernetes:
        enabled: true
        namespace: default
        service-label-name: hazelcastClusterName
        service-label-value: studio_hazelcast_cluster
        resolve-not-ready-addresses: true